name: Run Python Script and Create Release Branch
on:
  push:
    branches: [ master ]
  
permissions:
  contents: write  # Required for git push

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Create Release Branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git fetch --prune --tags
        
        RELEASE_BRANCH="release-$(TZ=Asia/Kolkata date -u +'%Y-%m-%d-%H%M%S')"
        echo "Creating release branch: $RELEASE_BRANCH"
        
        if git ls-remote --exit-code --heads origin "$RELEASE_BRANCH" > /dev/null 2>&1; then
          echo "Release branch already exists. Skipping creation."
        else
          git checkout -b "$RELEASE_BRANCH"
          git push origin "$RELEASE_BRANCH"
          echo "Release branch '$RELEASE_BRANCH' pushed successfully."
        fi
